// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: port/chat_port.proto

package port

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 消息
type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgName string `protobuf:"bytes,1,opt,name=msg_name,json=msgName,proto3" json:"msg_name,omitempty"` // 协议名
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                      // 数据
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *Msg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 返回给客户端的消息
type MsgReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgName string `protobuf:"bytes,1,opt,name=msg_name,json=msgName,proto3" json:"msg_name,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // 数据
}

func (x *MsgReturn) Reset() {
	*x = MsgReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReturn) ProtoMessage() {}

func (x *MsgReturn) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgReturn.ProtoReflect.Descriptor instead.
func (*MsgReturn) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{1}
}

func (x *MsgReturn) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *MsgReturn) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 登录
type MsgLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MsgLogin) Reset() {
	*x = MsgLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLogin) ProtoMessage() {}

func (x *MsgLogin) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLogin.ProtoReflect.Descriptor instead.
func (*MsgLogin) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{2}
}

func (x *MsgLogin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 登录返回
type MsgLoginReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MsgLoginReturn) Reset() {
	*x = MsgLoginReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLoginReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLoginReturn) ProtoMessage() {}

func (x *MsgLoginReturn) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLoginReturn.ProtoReflect.Descriptor instead.
func (*MsgLoginReturn) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{3}
}

func (x *MsgLoginReturn) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 登出
type MsgLogout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *MsgLogout) Reset() {
	*x = MsgLogout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLogout) ProtoMessage() {}

func (x *MsgLogout) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLogout.ProtoReflect.Descriptor instead.
func (*MsgLogout) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{4}
}

func (x *MsgLogout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 登出返回
type MsgLogoutReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MsgLogoutReturn) Reset() {
	*x = MsgLogoutReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLogoutReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLogoutReturn) ProtoMessage() {}

func (x *MsgLogoutReturn) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLogoutReturn.ProtoReflect.Descriptor instead.
func (*MsgLogoutReturn) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{5}
}

func (x *MsgLogoutReturn) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 创建聊天室
type MsgCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *MsgCreate) Reset() {
	*x = MsgCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreate) ProtoMessage() {}

func (x *MsgCreate) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreate.ProtoReflect.Descriptor instead.
func (*MsgCreate) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{6}
}

func (x *MsgCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgCreate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// 创建聊天室返回
type MsgCreateReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MsgCreateReturn) Reset() {
	*x = MsgCreateReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCreateReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateReturn) ProtoMessage() {}

func (x *MsgCreateReturn) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateReturn.ProtoReflect.Descriptor instead.
func (*MsgCreateReturn) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{7}
}

func (x *MsgCreateReturn) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MsgCreateReturn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 加入聊天室
type MsgJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MsgJoin) Reset() {
	*x = MsgJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgJoin) ProtoMessage() {}

func (x *MsgJoin) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgJoin.ProtoReflect.Descriptor instead.
func (*MsgJoin) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{8}
}

func (x *MsgJoin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgJoin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 加入聊天室返回
type MsgJoinReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MsgJoinReturn) Reset() {
	*x = MsgJoinReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgJoinReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgJoinReturn) ProtoMessage() {}

func (x *MsgJoinReturn) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgJoinReturn.ProtoReflect.Descriptor instead.
func (*MsgJoinReturn) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{9}
}

func (x *MsgJoinReturn) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 在聊天室中说话， 发送消息
type MsgSay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Msg  []byte `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MsgSay) Reset() {
	*x = MsgSay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSay) ProtoMessage() {}

func (x *MsgSay) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSay.ProtoReflect.Descriptor instead.
func (*MsgSay) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{10}
}

func (x *MsgSay) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgSay) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MsgSay) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

// 在聊天室中说话， 发送消息 返回
type MsgSayReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MsgSayReturn) Reset() {
	*x = MsgSayReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSayReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSayReturn) ProtoMessage() {}

func (x *MsgSayReturn) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSayReturn.ProtoReflect.Descriptor instead.
func (*MsgSayReturn) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{11}
}

func (x *MsgSayReturn) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 退出聊天室
type MsgQuit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MsgQuit) Reset() {
	*x = MsgQuit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgQuit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgQuit) ProtoMessage() {}

func (x *MsgQuit) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgQuit.ProtoReflect.Descriptor instead.
func (*MsgQuit) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{12}
}

func (x *MsgQuit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgQuit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

//退出聊天返回
type MsgQuitReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MsgQuitReturn) Reset() {
	*x = MsgQuitReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_port_chat_port_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgQuitReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgQuitReturn) ProtoMessage() {}

func (x *MsgQuitReturn) ProtoReflect() protoreflect.Message {
	mi := &file_port_chat_port_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgQuitReturn.ProtoReflect.Descriptor instead.
func (*MsgQuitReturn) Descriptor() ([]byte, []int) {
	return file_port_chat_port_proto_rawDescGZIP(), []int{13}
}

func (x *MsgQuitReturn) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_port_chat_port_proto protoreflect.FileDescriptor

var file_port_chat_port_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x70, 0x6f, 0x72, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x0a,
	0x08, 0x6d, 0x73, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3a, 0x0a, 0x09,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73, 0x67,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x73, 0x67,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1f, 0x0a, 0x09,
	0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x23, 0x0a,
	0x0f, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x35, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x33, 0x0a, 0x0f, 0x4d, 0x73, 0x67,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2d,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x21, 0x0a,
	0x0d, 0x4d, 0x73, 0x67, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x3e, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x53, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x20, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x53, 0x61, 0x79, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x2d, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x51, 0x75, 0x69, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x21, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x51, 0x75, 0x69, 0x74, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_port_chat_port_proto_rawDescOnce sync.Once
	file_port_chat_port_proto_rawDescData = file_port_chat_port_proto_rawDesc
)

func file_port_chat_port_proto_rawDescGZIP() []byte {
	file_port_chat_port_proto_rawDescOnce.Do(func() {
		file_port_chat_port_proto_rawDescData = protoimpl.X.CompressGZIP(file_port_chat_port_proto_rawDescData)
	})
	return file_port_chat_port_proto_rawDescData
}

var file_port_chat_port_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_port_chat_port_proto_goTypes = []interface{}{
	(*Msg)(nil),             // 0: Msg
	(*MsgReturn)(nil),       // 1: MsgReturn
	(*MsgLogin)(nil),        // 2: MsgLogin
	(*MsgLoginReturn)(nil),  // 3: MsgLoginReturn
	(*MsgLogout)(nil),       // 4: MsgLogout
	(*MsgLogoutReturn)(nil), // 5: MsgLogoutReturn
	(*MsgCreate)(nil),       // 6: MsgCreate
	(*MsgCreateReturn)(nil), // 7: MsgCreateReturn
	(*MsgJoin)(nil),         // 8: MsgJoin
	(*MsgJoinReturn)(nil),   // 9: MsgJoinReturn
	(*MsgSay)(nil),          // 10: MsgSay
	(*MsgSayReturn)(nil),    // 11: MsgSayReturn
	(*MsgQuit)(nil),         // 12: MsgQuit
	(*MsgQuitReturn)(nil),   // 13: MsgQuitReturn
}
var file_port_chat_port_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_port_chat_port_proto_init() }
func file_port_chat_port_proto_init() {
	if File_port_chat_port_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_port_chat_port_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLoginReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLogout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLogoutReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCreateReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgJoinReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSayReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgQuit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_port_chat_port_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgQuitReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_port_chat_port_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_port_chat_port_proto_goTypes,
		DependencyIndexes: file_port_chat_port_proto_depIdxs,
		MessageInfos:      file_port_chat_port_proto_msgTypes,
	}.Build()
	File_port_chat_port_proto = out.File
	file_port_chat_port_proto_rawDesc = nil
	file_port_chat_port_proto_goTypes = nil
	file_port_chat_port_proto_depIdxs = nil
}
